### ISSUE TITLE
CLINE won't initialize

### ISSUE THREAD

**Issue by darkstar4401** [cline/cline#570]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

GPT-4o

### What happened?

Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

Restarting extensions fails, updating or downgrading versions doesn't fix.

### Steps to reproduce

1.Install extension
2. select CLINE icon from sidebar
3. Get blank screen

**Comment by sched75** [comment]
gott the same issue since 1h. Was working nicely until now and I did change nothing.

**Comment by saoudrizwan** [comment]
Hello @darkstar4401 @sched75 can you please do the following and let me know what you find:
1. Cmd/Ctrl + Shift + P > "Developer: Toggle Developer Tools"
2. Open the Console tab to see logs 
3. Try opening Cline again and see if any errors come up. 
It seems this issue might happen when the GUI webview runs into a typeerror for example. Any additional insight here would be helpful, thank you!

**Comment by lecajer** [comment]
Same error here on Windows WSL after installing v2.1.3
Details from the Output - Extension Host (Remote) :

```
[error] TypeError: (0 , p7.getDefaultHighWaterMark) is not a function
    at Object.<anonymous> (/home/me/.vscode-server/extensions/saoudrizwan.claude-dev-0.0.6/dist/extension.js:59:24554)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.u._load (/home/me/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:154:5631)
    at Function.c._load (/home/me/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:151:29196)
    at Function.t._load (/home/me/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:118:35261)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at Module.require (/home/me/.vscode-server/extensions/github.copilot-chat-0.8.0/dist/extension.js:17:42010)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Function.i [as __$__nodeRequire] (/home/me/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/loader.js:5:98)
    at s.vb (/home/me/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:151:30375)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
```

**Comment by richeenjugush** [comment]
Did anyone find a fix for this issue?

**Comment by lecajer** [comment]
I managed to get the v2.1.5 working by installing the extension from a file :
- Update VS Code
- Download the `.vsix` file from the [Vs Code Marketplace website](https://marketplace.visualstudio.com/items?itemName=saoudrizwan.claude-dev&ssr=false#version-history)
- Extensions -> ... -> Install from VSIX...

![image](https://github.com/user-attachments/assets/dc09fa17-e92b-49d1-9e7b-7c47b5790396)
Before updating VS Code I got this error
`Unable to install extension 'saoudrizwan.claude-dev' as it is not compatible with VS Code '1.83.1'.`

--

There is an issue when installing from VS Code on windows it switch to a old version
![image](https://github.com/user-attachments/assets/ca2372b6-0b8f-4831-b723-5eb340b43166)

**Comment by haritsE** [comment]
I had the same issue as @lecajer and @ranand12. What fixed it for me was to reinstall the latest version of VS Code.

My VSCode version now:

![Image](https://github.com/user-attachments/assets/2b9462af-95f9-45a0-9934-7c43e765aaf7)

**Comment by jeff14994** [comment]
Encountered the same issue, update to VSCode (Version: 1.109.0
Commit: bdd88df003631aaa0bcbe057cb0a940b80a476fa) works
