### ISSUE TITLE
stuck at cline wants to use the browser:

### ISSUE THREAD

**Issue by byjlw** [cline/cline#732]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

sonnet-3.5

### What happened?

can't use the browser action

### Steps to reproduce

1.Trying out cline for the first time. 
2.Added my openrouter key

2. Asked for the weather in seattle
3: when asked to approve i clicked approve 
4. Just spins

![Screenshot from 2024-11-13 21-44-02](https://github.com/user-attachments/assets/0e23837f-189b-4889-a6c8-2581c3812396)

### Additional context

Ubuntu OS

**Comment by steiner385** [comment]
I'm having the exact same issue, but running on windows 11 and using the anthropic as provider.

**Comment by MatthewDailey** [comment]
+1 on osx with anthropic. It eventually timed out.

```
The tool execution failed with the following error:
<error>
Error executing browser action: {"name":"Yle","message":"Page.captureScreenshot timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.","stack":"Yle: Page.captureScreenshot timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.\n    at zAe.<instance_members_initializer> (/Users/mjd/.vscode/extensions/saoudrizwan.claude-dev-2.1.6/dist/extension.js:579:91505)\n    at new zAe (/Users/mjd/.vscode/extensions/saoudrizwan.claude-dev-2.1.6/dist/extension.js:579:91569)\n    at vUe.create (/Users/mjd/.vscode/extensions/saoudrizwan.claude-dev-2.1.6/dist/extension.js:579:90716)\n    at wUe._rawSend (/Users/mjd/.vscode/extensions/saoudrizwan.claude-dev-2.1.6/dist/extension.js:579:95662)\n    at yUe.send (/Users/mjd/.vscode/extensions/saoudrizwan.claude-dev-2.1.6/dist/extension.js:579:92630)\n    at t._screenshot (/Users/mjd/.vscode/extensions/saoudrizwan.claude-dev-2.1.6/dist/extension.js:591:71630)\n    at t.screenshot (/Users/mjd/.vscode/extensions/saoudrizwan.claude-dev-2.1.6/dist/extension.js:579:75265)\n    at t.<anonymous> (/Users/mjd/.vscode/extensions/saoudrizwan.claude-dev-2.1.6/dist/extension.js:579:10905)\n    at Y1e.doAction (/Users/mjd/.vscode/extensions/saoudrizwan.claude-dev-2.1.6/dist/extension.js:1541:13319)\n    at nK.presentAssistantMessage (/Users/mjd/.vscode/extensions/saoudrizwan.claude-dev-2.1.6/dist/extension.js:1594:4632)"}
</error>
```

**Comment by andrewkmin** [comment]
+1 on this; can repro on macOS

**Comment by themightychris** [comment]
There was a few days where the nightly build of chromium it downloads automatically was broken. Then it gets cached and Cline will never try to download an open one on its own. I'm on mobile so I can't find the exact path right now it's somewhere under Library Support on Mac where all VSCode extensions get to store stuff. Delete it and restart to get a fresh chromium build

**Comment by bom-sourcingguide** [comment]
Also stuck browsing localhost on windows 10, open router, deep seek

**Comment by chen2438** [comment]
+1 on MacOS 15.3. Cline got 403 while using browser. However, I can access localhost server mannally (through Edge).

<img width="488" alt="Image" src="https://github.com/user-attachments/assets/981ed0dc-fe18-4fb9-b3db-ec5b0ad34796" />

**Comment by aaurelions** [comment]
After about 5 minutes, everything will work, expect it.

<img width="389" alt="Image" src="https://github.com/user-attachments/assets/730c26cf-5224-4496-ba1b-e1d65c62799f" />

<img width="387" alt="Image" src="https://github.com/user-attachments/assets/e5e9e073-95d2-456b-b549-363461f4f57b" />

**Comment by tonywang10101** [comment]
> After about 5 minutes, everything will work, expect it.
> 
> <img alt="Image" width="389" src="https://private-user-images.githubusercontent.com/190230274/422874039-730c26cf-5224-4496-ba1b-e1d65c62799f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQxODUyODksIm5iZiI6MTc0NDE4NDk4OSwicGF0aCI6Ii8xOTAyMzAyNzQvNDIyODc0MDM5LTczMGMyNmNmLTUyMjQtNDQ5Ni1iYTFiLWUxZDY1YzYyNzk5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDQwOVQwNzQ5NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjU0ODAzNWQ3MzlkNWM1MzkzNWNlZjdkZDdmODZiNTg4OTc3OTM2MTNmYTU1ZDdlNzEyYzJmNTFjOTlmMDIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.acCkNWB_eqyrDjgVQHYmYgM1tGkuDhg0tzdEUGb1p3s"> <img alt="Image" width="387" src="https://private-user-images.githubusercontent.com/190230274/422875362-e5e9e073-95d2-456b-b549-363461f4f57b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQxODUyODksIm5iZiI6MTc0NDE4NDk4OSwicGF0aCI6Ii8xOTAyMzAyNzQvNDIyODc1MzYyLWU1ZTllMDczLTk1ZDItNDU2Yi1iNTQ5LTM2MzQ2MWY0ZjU3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDQwOVQwNzQ5NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTQxMWExYmU2ZDMyYTRkMDE4NTY3MjRiYWEzMzk2ZDRjNjk4YjFlYjJmMzRmZTNlYzhkMDFhMDNmMDE2YWIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Dya7iLxBarfIQU_PU-q8QKbRFeEQRgcopvSZdt9V1cg">

I Met the same issue

<img width="319" alt="Image" src="https://github.com/user-attachments/assets/70af0d43-6bfa-4e02-b896-5da5b9dca490" />
