### ISSUE TITLE
Cline Extension Fails to Activate in Remote SSH Environment on VSCodium (and probably also on VSCode)

### ISSUE THREAD

**Issue by spechtx** [cline/cline#886]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

Claude 3.5 Sonnet

### What happened?

The Cline extension fails to activate when used in a remote SSH environment, while working correctly in the local VSCodium installation.

### Steps to reproduce

1. Connect to remote environment using Open Remote SSH Extension (in VSCode this is Microsoft Remote - SSH)
2. Click on the Cline extension icon in the sidebar
3. Extension shows loading icon but fails to activate

### Additional context

**Observed Behavior:**
1. Extension fails to activate
2. Error logged in "Extension Host (Remote)":
```
[error] ReferenceError: ReadableStream is not defined
    at /home/[user]/.vscodium-server/extensions/saoudrizwan.claude-dev-2.1.6-universal/dist/extension.js:502:14488
```
3. Cline is missing in the **remote** OUTPUT section dropdown, indicating that the issue appears before it the extension is registered. All other extension are activated.
![remote](https://github.com/user-attachments/assets/e9c0154e-5854-4d9d-991d-34a603cbb4ca)

For Comparison, this is the **local** OUTPUT section for Cline:
![local](https://github.com/user-attachments/assets/921452e4-32f9-4044-b201-5b5427a40643)

4. Additional error in "Remote Tunnel Service" (_that shows also on the local instance where Cline works - so this is probably unrelated and could indicate strict sshd_config_):
`[error] Missing 'tunnelApplicationConfig' or 'tunnelApplicationName' in product.json. Remote tunneling is not available.`

**Expected Behavior:**
- Cline extension should activate and function in remote environment as it does locally
- Extension should appear in Output section selection
- No ReadableStream-related errors

**Additional Notes:**
- The extension activates successfully in local environment
- Other extensions are working in the remote environment

This is the full error log from the "Extension Host (Remote)" Secion in OUTPUT
```
[info] ExtensionService#_doActivateExtension saoudrizwan.claude-dev, startup: false, activationEvent: 'onView:claude-dev.SidebarProvider'
[error] Activating extension saoudrizwan.claude-dev failed due to an error:
[error] ReferenceError: ReadableStream is not defined
at /home/[user]/.vscodium-server/extensions/saoudrizwan.claude-dev-2.1.6-universal/dist/extension.js:502:14488
at /home/[user]/.vscodium-server/extensions/saoudrizwan.claude-dev-2.1.6-universal/dist/extension.js:1:357
at /home/[user]/.vscodium-server/extensions/saoudrizwan.claude-dev-2.1.6-universal/dist/extension.js:502:27736
at /home/[user]/.vscodium-server/extensions/saoudrizwan.claude-dev-2.1.6-universal/dist/extension.js:1:357
at /home/[user]/.vscodium-server/extensions/saoudrizwan.claude-dev-2.1.6-universal/dist/extension.js:503:6108
at /home/[user]/.vscodium-server/extensions/saoudrizwan.claude-dev-2.1.6-universal/dist/extension.js:1:357
at Object.<anonymous> (/home/[user]/.vscodium-server/extensions/saoudrizwan.claude-dev-2.1.6-universal/dist/extension.js:920:180062)
at Module._compile (node:internal/modules/cjs/loader:1198:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
at Module.load (node:internal/modules/cjs/loader:1076:32)
at Function.Module._load (node:internal/modules/cjs/loader:911:12)
at Function.e._load (file:///home/[user]/.vscodium-server/bin/[id]/out/vs/workbench/api/node/extensionHostProcess.js:174:12010)
at Function.t._load (file:///home/[user]/.vscodium-server/bin/[id]/out/vs/workbench/api/node/extensionHostProcess.js:166:28448)
at Function.i._load (file:///home/[user]/.vscodium-server/bin/[id]/out/vs/workbench/api/node/extensionHostProcess.js:158:5023)
at Module.require (node:internal/modules/cjs/loader:1100:19)
at require (node:internal/modules/cjs/helpers:119:18)
at VB._loadCommonJSModule (file:///home/[user]/.vscodium-server/bin/[id]
/out/vs/workbench/api/node/extensionHostProcess.js:166:30081)
at async Promise.all (index 0)
```

Related issues:
#430
#807 
#587

**Comment by saoudrizwan** [comment]
Thank you for sharing all the details, cline runs into issues in remote–I'll have to dig into the vs code docs and figure out what's going on but if anyone has any pointers here I'd appreciate them.

**Comment by spechtx** [comment]
I not yet dug deep into this. A vague guess is, that the extension may require a newer version of Node.js that includes ReadableStream as part of the Web Streams API. Maybe a polyfill for ReadableStream in environments where it's not natively available could resolve the issue? Like i mentioned, its just a guess. VSCodium server environment may not have web APIs fully configured that would normally be available in a browser context.

**Comment by makinghappen** [comment]
@spechtx @saoudrizwan is there a workaround to install newer node.js?

**Comment by Wenbo94** [comment]
opened my vscode developer tools in romote env and I saw some proxy error in the console. guess maybe cline in remote env want to use the local env proxy settings.
after created a new config file for remote project and set http.proxy to null.  everythings works for me .

**Comment by orangejon** [comment]
Just in case it helps: Cline is working perfectly for me using Vscode locally but connected to a Github Codespace. (which is essentially a Ubuntu linux virtual machine via SSH)

**Comment by PoliTwit1984** [comment]
Cline works fine for me when i use ssh to replit - using VS Code

**Comment by MyrddinE** [comment]
Cline is failing for me, I'm SSH'd into my Linux VPS which I use for coding and hosting my hobby projects. It works fine when running locally.

This is using VS Code, and Remote - SSH. The remote system is Ubuntu 24.04 LTS. I fresh installed VS Code to a new system with only two plugins (Remote - SSH and Cline) and the problem persists. As the OP mentioned, Cline works locally, and the Remote SSH session seems to be working perfectly.

**Comment by MyrddinE** [comment]
I was doing some additional tests this weekend, attempting to discover the cause of the issue. This may be relevant:
```
2025-02-02 18:27:49.883 [info] ExtensionService#_doActivateExtension saoudrizwan.claude-dev, startup: false, activationEvent: 'onView:claude-dev.SidebarProvider'
2025-02-02 18:27:56.491 [error] Error: Task not found
	at t.getTaskWithId (/home/myrddin/.vscode-server/extensions/saoudrizwan.claude-dev-3.2.12/dist/extension.js:2438:14882)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async t.showTaskWithId (/home/myrddin/.vscode-server/extensions/saoudrizwan.claude-dev-3.2.12/dist/extension.js:2438:14980)
```

Is it possible that the `onView` event isn't sent to the remote system? I'm seeing this output for the Cline extension: 
```
Cline extension activated
ClineProvider instantiated
Resolving webview view
Webview view resolved
```
But on the remote server, I'm net seeing any process running for `claude-dev`, nor does the *Remote - SSH* log get any new entries when I open the Cline sidebar.

**Comment by flo090688** [comment]
Is there an update on this topic? 
The Cline extension still cannot be installed remotely and is stuck in the "Activating" stage. 
I use DevPod with a Kubernetes provider. In VS Code (as a desktop IDE) it works. But not via VS Code Browser. Strange...

**Comment by geilsonrm** [comment]
I had the same problem and in my case it was permission to access the folder in the file system. VSCode (via the Cline extension) did not have permission to read the folder. I don't know if this is the best way, but I solved it with ChatGPT's tip:

1. Give permission to the folder to the pi user:
sudo chown -R pi:pi /home/pi/geilson/docker-evo/api_evolution

2. (Optional) Make sure VSCode can read everything:
chmod -R 755 /home/pi/geilson/docker-evo/api_evolution

**Comment by MyrddinE** [comment]
This seems implausible as a reason, since Cline re-uses the existing ssh connection that is established, and with that connection I have the ability to manually do all the tasks I'm asking of Cline. I'm not sure where you are coming up with a 'pi user'. The process of connecting to a remote system in VS Code uses your existing user credentials generally.

Your particular remote system may have a `pi` account, but I don't think that generalizes to this overall issue, unless I'm misunderstanding.

**Comment by besc22** [comment]
Same problem here for vscode. After activating cline with anthropic in an ssh host, I see the history and so on, but when I want to start a new task it just says: Loading...

**Comment by l0nedigit** [comment]
For what it's worth, I had the same issue.  Cline worked locally.  Would fail using a Remote-SSH session, saying Connection error.  

I closed vscode, installed the latest and now it seems to work correctly in a remote ssh session.

Will update if it happens again.  But for reference here is the exact version I was running and updated to:
Unpacking code (1.100.2-1747260578) over (1.99.3-1744761595) ...
Setting up code (1.100.2-1747260578) ...

**Comment by celestial-vault** [comment]
Thanks for the detailed technical report! This issue has been consolidated into the comprehensive remote SSH workspace support feature request #4352.

The specific ReadableStream error you identified provides valuable debugging information for the implementation team. This technical issue, along with the community workarounds mentioned in the comments (proxy settings, VSCode updates), will be addressed as part of the broader remote workspace improvements.
