### ISSUE TITLE
Unable to fetch models from OpenRouter

### ISSUE THREAD

**Issue by admSla99** [cline/cline#892]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

Google Gemini 2.0 flash experimental

### What happened?

I want to try out multiple models provided by OpenRouter. But I think Cline is unable to fetch models from OpenRouter. When I choose API provider OpenRouter and place API key here then model dropdown is empty and whatever I try to write here doesn't help. I also try to copy exact name of model from OpenRouter web to Cline but it didn't help. It says that model name doesn't exist.

### Steps to reproduce

1. Just install Cline
2. Choose OpenRouter like API provider
3. Choose model

**Comment by libertyteeth** [comment]
FYI, I started using OpenRouter months ago because Cline wasn't rate-limiting, and Anthropic kept slowing it down.  OpenRouter handled the rate-limiting, in between, which was helpful in keeping pace.

A week or two ago OpenRouter had an outage of some sort, and I connected directly to Anthropic.  My use case may be Claude-specific; that said, in my case, the middleman is not necessary any longer.

**Comment by saoudrizwan** [comment]
@admSla99 this might happen if the request to https://openrouter.ai/api/v1/models fails in the background... does restarting vs code not fix this issue for you?

**Comment by admSla99** [comment]
@saoudrizwan link opened via browser works, so seems like problem its fetch from cline. Yes I try restart VS code and reinstall Cline too, didnt help.

**Comment by zgldh** [comment]
You can check the vscode "OUTPUT" tab, the "Window" output. Search "saoudrizwan" and maybe you can see something clue

**Comment by JohnnyBao-1993** [comment]
i have the same issue here, i`m working behind a proxy server

**Comment by winteryoung** [comment]
> i have the same issue here, i`m working behind a proxy server and from the output windows i can see following error: 2024-12-30 22:05:08.633 [error] [Extension Host] Invalid response from OpenRouter API
> 
> but from terminal in vs code i can run curl https://openrouter.ai/api/v1/models i can get correct response with 200 status.
> 
> any idea?

Same here. I first pasted my openrouter api key directly after first installing cline. Didn't click "Get OpenRouter API Key" first. Maybe that's the trigger?

**Comment by winteryoung** [comment]
For a quick fix, I suggest don't do verification on setting update. Currently the model text must match the ones in the model list cache, which is empty if this bug occurred. As a programmer user, we can get the exact model name from openrouter manually, which is not a problem for most of us.

**Comment by admSla99** [comment]
@winteryoung can you be please more detailed ? Where model definition in cache is located ? When I defined model name manualy in Model section it says "model with that ID doesnt exist". I think problem is working behind proxy and extension doesnt load proxy setting from env.

**Comment by tedyyu** [comment]
The same issue was encountered today in cline 3.8.6, behind a firewall on mac.

**Comment by haha110110** [comment]
I have the same problem after upgrade to 3.91 on ssh-remote. and not just openrouter fetch problems also other provider shows 401 wrong key. I pretty sure the key is right.

**Comment by AInseven** [comment]
This happened when I set an environmental variable HTTPS_PROXY.
```shell
2025-04-10 16:19:35.170 [error] [Window] [Extension Host] Error fetching OpenRouter models: AxiosError: Request failed with status code 400
    at yI (c:\Users\Administrator\.vscode\extensions\saoudrizwan.claude-dev-3.10.1\dist\extension.js:1020:1051)
    at IncomingMessage.<anonymous> (c:\Users\Administrator\.vscode\extensions\saoudrizwan.claude-dev-3.10.1\dist\extension.js:1021:9748)
    at IncomingMessage.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at eL.request (c:\Users\Administrator\.vscode\extensions\saoudrizwan.claude-dev-3.10.1\dist\extension.js:1023:2057)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at tKe.refreshOpenRouterModels (c:\Users\Administrator\.vscode\extensions\saoudrizwan.claude-dev-3.10.1\dist\extension.js:2698:1833)
```
And in the proxy logs, receive this msg:
2025/04/10 16:28:13 from 127.0.0.1:3778 accepted **https://openrouter.ai/api/v1/models** [socks >> proxy]

When I curl in CMD, it works well.
```bash
curl https://openrouter.ai/api/v1/models
```
The proxy log is:
2025/04/10 16:29:28 from 127.0.0.1:9331 accepted **//openrouter.ai:443** [socks >> proxy]

**Comment by AInseven** [comment]
For those who use proxy, I have found a solution. In windows 11 environmental variable, delete https_proxy, only remain http_proxy. Then restart VS code.

**Comment by winteryoung** [comment]
> [@winteryoung](https://github.com/winteryoung) can you be please more detailed ? Where model definition in cache is located ? When I defined model name manualy in Model section it says "model with that ID doesnt exist". I think problem is working behind proxy and extension doesnt load proxy setting from env.

Yeah, it's a proxy setting thing. Like @AInseven said, removing https_proxy makes the problem go away. But some tools like uv in python, requires the presence of https_proxy for it to use a proxy correctly.

**Comment by d416** [comment]
We need proper axios-level proxy settings enabled in Cline to accommodate enterprise proxy configurations that are unique to the organization. Cline just defers to the axios default proxy env variable handling which appears to work in most cases, but at my office the proxy uses its own cert and tunneling fails with cline (‘TypeError fetch failed’ in my case). This can be resolved by explicitly setting proxies in axios options.

**Comment by celestial-vault** [comment]
Thanks for the suggestion! This has been consolidated into #4355.
